name: flutter_autostart_android
description: "A Flutter port of the Android AutoStarter library that helps bring up the autostart permission manager on various OEM devices."
version: 1.0.0
homepage: https://github.com/aminnez/flutter_autostart_android
repository: https://github.com/aminnez/flutter_autostart_android

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ">=4.0.0 <6.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.aminnez.flutter_autostart_android
        pluginClass: FlutterAutostartAndroidPlugin
